[phases.setup]
nixPkgs = ["nodejs_20", "python311", "pkg-config", "yarn-1_x"]

[phases.install]
cmds = ["cd server && yarn install"]

[phases.build]
cmds = ["cd server && yarn build"]

[start]
cmd = "cd server && yarn start"
